# Generated by Django 5.1.4 on 2024-12-08 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreview',
            name='stars_given',
        ),
    ]
