# Generated by Django 5.1.4 on 2024-12-08 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_productreview_stars_given'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageview',
            name='session_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
