# Generated by Django 5.1.4 on 2024-12-08 06:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_pageview_session_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Действие пользователя', 'verbose_name_plural': 'Действия пользователей'},
        ),
        migrations.RemoveField(
            model_name='useraction',
            name='action',
        ),
        migrations.RemoveField(
            model_name='useraction',
            name='item_id',
        ),
        migrations.RemoveField(
            model_name='useraction',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='useraction',
            name='action_type',
            field=models.CharField(choices=[('ADD_TO_FAVORITE', 'Добавление в избранное'), ('PLACE_ORDER', 'Оформление заказа'), ('WRITE_REVIEW', 'Написание отзыва')], default=1, max_length=20, verbose_name='Тип действия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraction',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время действия'),
        ),
        migrations.AddField(
            model_name='useraction',
            name='target_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_actions', to='products.order', verbose_name='Целевой заказ'),
        ),
        migrations.AddField(
            model_name='useraction',
            name='target_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_actions', to='products.product', verbose_name='Целевой продукт'),
        ),
        migrations.AlterField(
            model_name='useraction',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
